version: '3.9'
services:
  trino:
    hostname: trino
    image: 'trinodb/trino:390'
    user: root
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc
      - ./catalog:/etc/trino/catalog

#  postgres:
#    ports:
#      - "5432:5432"
#    image: postgres:11
#    container_name: postgres
#    environment:
#      POSTGRES_USER: trino
#      POSTGRES_PASSWORD: trino

  metastore_db:
    ports:
      - "5432:5432"
    image: postgres:11
    hostname: metastore_db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore

  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      - metastore_db

  minio:
    hostname: minio
    #    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    image: 'quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
#    volumes:
#      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
  # This job will create the "datalake" bucket on Minio
  mc-job:
    image: 'minio/mc:RELEASE.2022-05-09T04-08-26Z'
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add myminio http://minio:9000 minio_access_key minio_secret_key;
      /usr/bin/mc mb --quiet myminio/datalake
      /usr/bin/mc mb --quiet myminio/warehouse
      "
    depends_on:
      - minio
  test:
    image: python:3.10-alpine
    command: ["./test.sh"]
    profiles:
      - dev
    working_dir: /scripts
    volumes:
      - ./scripts:/scripts
    environment:
      - HIVE_HOST=hive-metastore
      - HIVE_PORT=9083

#volumes:
#  minio-data:
#    driver: local
